server.port=8080
github.username=jagannathsaha04
github.api.base-url=https://api.github.com
github.token=${GITHUB_TOKEN:}
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=3600s
